name: CMake Multi-Platform Build

on:
  workflow_dispatch:
  push:
    tags:
      - "release/*"

jobs:
  build:
    name: "${{ matrix.os }} | ${{ matrix.compiler }}"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          # =====================
          # Linux
          # =====================
          - os: linux
            compiler: gcc
            runner: ubuntu-latest
            cc: gcc
            cxx: g++

          - os: linux
            compiler: clang
            runner: ubuntu-latest
            cc: clang
            cxx: clang++

          # =====================
          # Windows
          # =====================
          - os: windows
            compiler: msvc
            generator: Visual Studio 17 2022
            runner: windows-latest

          - os: windows
            compiler: gcc
            runner: windows-latest
            cc: gcc
            cxx: g++

          - os: windows
            compiler: clang
            runner: windows-latest
            cc: clang
            cxx: clang++

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: cmake -S . -B build -G "${{ matrix.generator || 'Ninja' }}" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Install and Package
        if: github.ref_type == 'tag'
        run: |
          mkdir dist
          cd dist
          cpack --config ../build/CPackConfig.cmake -D CPACK_PACKAGE_FILE_NAME=dist

      - name: Upload Packages
        if: github.ref_type == 'tag'
        run: |
          for file in dist/*; do
            [ -f "$file" ] || continue

            base="$(basename "$file")"
            ext="${base#*.}"

            target="dist/unvm-${{ github.ref_name }}-${{ matrix.os }}-${{ matrix.compiler }}.${ext}"

            mv "$file" "$target"
            gh release upload ${{ github.ref_name }} "$target" --clobber
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
