name: CMake Multi-Platform Build

on:
  workflow_dispatch:
  push:
    tags:
      - "release/*"

jobs:
  build:
    name: "${{ matrix.os }} | ${{ matrix.toolchain }}"
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        include:
          # =====================
          # Linux
          # =====================
          - os: linux
            runner: ubuntu-latest
            triplet: x64-linux
            toolchain: gcc
            cc: gcc
            cxx: g++

          - os: linux
            runner: ubuntu-latest
            triplet: x64-linux
            toolchain: clang
            cc: clang
            cxx: clang++

          # =====================
          # Windows
          # =====================
          - os: windows
            runner: windows-latest
            triplet: x64-windows
            toolchain: msvc
            generator: Visual Studio 17 2022

          - os: windows
            runner: windows-latest
            triplet: x64-windows
            toolchain: clang
            cc: clang
            cxx: clang++

          # =====================
          # Darwin
          # =====================
          - os: darwin
            runner: macos-latest
            triplet: arm64-osx
            toolchain: gcc
            cc: gcc
            cxx: g++

          - os: darwin
            runner: macos-latest
            triplet: arm64-osx
            toolchain: clang
            cc: clang
            cxx: clang++

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Sanitize Version Name
        id: version-name
        if: github.ref_type == 'tag'
        run: |
          ref="${{ github.ref_name }}"
          
          version="${ref##*/}"
          version="${version#v}"
          version=$(echo "$version" | sed 's/[^a-zA-Z0-9._-]/-/g')
          
          if [[ "$version" =~ ^[0-9]+(\.[0-9]+)+([._-][A-Za-z0-9]+)?$ ]]; then
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            echo "version=0.0.0"
          fi
        shell: bash

      - name: Setup vcpkg
        id: vcpkg
        uses: johnwason/vcpkg-action@v7
        with:
          pkgs: libarchive openssl
          triplet: ${{ matrix.triplet }}-release
          token: ${{ github.token }}
          cache-key: vcpkg-${{ matrix.os }}-${{ matrix.toolchain }}

      - name: Configure CMake
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: >
          cmake
          -S .
          -B build
          -G "${{ matrix.generator || 'Ninja' }}"
          -DCMAKE_BUILD_TYPE=Release
          -DUNVM_PROJECT_VERSION='${{ steps.version-name.outputs.version }}'
          ${{ steps.vcpkg.outputs.vcpkg-cmake-config }}

      - name: Build
        run: cmake --build build --config Release --parallel

      - name: Install and Package
        if: github.ref_type == 'tag'
        run: |
          mkdir dist
          cd dist
          cpack --config ../build/CPackConfig.cmake -D CPACK_PACKAGE_FILE_NAME=dist

      - name: Upload Packages
        if: github.ref_type == 'tag'
        run: |
          for file in dist/*; do
            [ -f "$file" ] || continue

            ext="$(basename "$file")"
            ext="${ext#*.}"

            target="dist/unvm-${{ steps.version-name.outputs.version }}-${{ matrix.os }}-${{ matrix.toolchain }}.${ext}"

            mv "$file" "$target"

            echo "Upload $target to ${{ github.ref_name }}"
            gh release upload ${{ github.ref_name }} "$target" --clobber
          done
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
